author: "Tobe O <thosakwe@gmail.com>"
description: "Helper library for language tooling with Dart."
environment:
  sdk: ">=1.19.0"
homepage: "https://github.com/thosakwe/compiler_tools.git"
name: "compiler_tools"
version: "1.0.0-dev"
dependencies: 
  charcode: "^1.1.1"
  source_maps: "^0.10.2"
  source_span: "^1.3.0"
  string_scanner: "^1.0.1"
